identifier = "org.fs.chm"

[build]
beforeDevCommand = "pnpm dev"
beforeBuildCommand = "pnpm generate"
devUrl = "http://localhost:3000"
frontendDist = "./frontend/out"

[app]
# Injects window.__TAURI__ global variable
withGlobalTauri = true

[[app.windows]]
title = "Hello, Tauri!"
fullscreen = false
width = 800
height = 600
resizable = true

[bundle]
# Can't find a way to get rid of these icons
icon = [
  "frontend/src/app/32x32.png",
  "frontend/src/app/icon.icns",
  "frontend/out/favicon.ico",
]
